### ISSUE TITLE
Create support matrix

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/sig-release#6]
We should have a simple matrix for our KubeVirt-to-K8s version support. This repo seems like the logical place for it.

Context:
              > We are confused if 0.58 supports k8s 1.25.

v0.58.0 has not been tested against k8s 1.25. It should work though, but if you need 'official' support statement, you probably need to switch to the latest KubeVirt v0.59.0.

> It will be really helpful if you can provide the documentation that specifies the compatibility matrix for various versions.

Yeah, that is now missing. Agree, it would be useful to have such a matrix.

_Originally posted by @vasiliy-ul in https://github.com/kubevirt/kubevirt/issues/8482#issuecomment-1477355609_

**Comment by fabiand** [comment]
On it.

**Comment by aburdenthehand** [comment]
Fabian's PR [#9982](https://github.com/kubevirt/kubevirt/pull/9982) on kubevirt/kubevirt added version support and lifecycle information to [docs/release.md](https://github.com/kubevirt/kubevirt/blob/main/docs/release.md#platform-support). 

I still think it would be useful to have a matrix in this repo that clearly shows the version's currently supported plotted against the supported k8s versions, but there would be overhead to keep it current.

**Comment by aburdenthehand** [comment]
Completed by #13
